version: '2'
services:
  mdns:
    build: ./mdns
    privileged: true
    restart: always
    network_mode: "host"
    labels:
      io.balena.features.dbus: '1'
  player:
    build: ./player
    privileged: true
    restart: always
    network_mode: "host"
    labels:
      io.balena.features.kernel-modules: '1'
